bucket4j:
  enabled: true
  filters:
    - cache-name: dw2-rate-limit
      url: /api.*
      http-response-body: "{ \"message\" : \"You have exhausted your API request limit\" }"
      rate-limits:
      - bandwidths:
        - capacity: 100
          time: 1
          unit: seconds

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    baggage:
      correlation:
        enabled: true
    sampling:
      probability: 1.0
    
server:
  port: 8094

service:
  welcome:
    message: Hello from local dw2-svc

spring:
  application:
    name: dw2-svc
  boot:
    admin:
      client:
        url: http://localhost:8763
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    cache-names: dw2-rate-limit
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: ${DW2_DB_URL}
    username: ${DW2_USER}
    password: ${DW2_PASS}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      idle-timeout: 20000
      pool-name: DW2-CP
      maximum-pool-size: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
